package ai.oya.keel.codegen;

import ai.oya.keel.ApiError;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * dag.json → job.py, in a shape a test can hold: one function per node, `main()` wiring them in
 * topological order. Every literal passes through {@link #py(Object)}; nothing from the DAG is
 * concatenated into Python as raw text. Unknown node types are an error that names the node.
 */
public final class PySpark {
    private PySpark() {}

    public record Generated(String script, Map<String, int[]> ranges, Map<String, String> names) {}

    public static Generated generate(JsonNode dagJson) {
        Dag dag = Dag.parse(dagJson);
        List<Dag.Node> order = dag.topo();
        Map<String, String> names = Dag.snakeNames(order);
        StringBuilder out = new StringBuilder();
        out.append("# Generated by Keel from dag.json. Do not edit by hand: custom logic belongs in a SparkSQL or CustomCode node.\n")
           .append("import re\nimport sys\n\n")
           .append("from awsglue.context import GlueContext\nfrom awsglue.dynamicframe import DynamicFrame, DynamicFrameCollection\n")
           .append("from awsglue.job import Job\nfrom awsglue.transforms import ApplyMapping, DropFields, DropNullFields, Filter, Join, RenameField, SelectFields\n")
           .append("from awsglue.utils import getResolvedOptions\nfrom pyspark.context import SparkContext\nfrom pyspark.sql import functions as F\n");
        for (Dag.Node n : order) {
            if (!n.type().equals("CustomCode")) continue;
            String lang = n.body().path("Language").asText("PYTHON3");
            if (!lang.toUpperCase().startsWith("PYTHON")) throw unsupported(n, "CustomCode in " + lang);
            out.append("\n\n# --- CustomCode: ").append(n.name()).append(" ---\n").append(n.body().path("Code").asText().strip()).append('\n');
        }
        Map<String, int[]> ranges = new LinkedHashMap<>();
        for (Dag.Node n : order) {
            String fn = function(n, names, dag);
            int start = lines(out) + 3; // after the two blank lines
            out.append("\n\n").append(fn);
            ranges.put(n.id(), new int[] {start, lines(out)});
        }
        out.append("\n\ndef main():\n    args = getResolvedOptions(sys.argv, [\"JOB_NAME\"])\n    sc = SparkContext.getOrCreate()\n")
           .append("    glueContext = GlueContext(sc)\n    job = Job(glueContext)\n    job.init(args[\"JOB_NAME\"], args)\n");
        for (Dag.Node n : order) {
            out.append("    f_").append(names.get(n.id())).append(" = ").append(names.get(n.id())).append("(glueContext");
            for (String in : n.inputs()) out.append(", f_").append(names.get(in));
            out.append(")\n");
        }
        out.append("    job.commit()\n\n\nif __name__ == \"__main__\":\n    main()\n");
        return new Generated(out.toString(), ranges, names);
    }

    private static int lines(StringBuilder b) { int n = 0; for (int i = 0; i < b.length(); i++) if (b.charAt(i) == '\n') n++; return n; }

    static String function(Dag.Node n, Map<String, String> names, Dag dag) {
        JsonNode b = n.body();
        String id = py(n.id());
        List<String> params = new ArrayList<>();
        params.add("glueContext");
        for (String in : n.inputs()) params.add(names.get(in));
        StringBuilder f = new StringBuilder();
        String body;
        switch (n.type()) {
            case "S3CsvSource" -> {
                params.add("paths=" + py(b.path("Paths")));
                body = "    return glueContext.create_dynamic_frame.from_options(\n        connection_type=\"s3\",\n        format=\"csv\",\n"
                        + "        format_options={\"withHeader\": " + py(b.path("WithHeader").asBoolean(true)) + ", \"separator\": " + py(separator(b.path("Separator").asText("comma")))
                        + ", \"quoteChar\": " + py(quote(b.path("QuoteChar").asText("quote"))) + (b.has("Multiline") ? ", \"multiline\": " + py(b.path("Multiline").asBoolean()) : "")
                        + (b.hasNonNull("Escaper") && !b.path("Escaper").asText().isEmpty() ? ", \"escaper\": " + py(b.path("Escaper").asText()) : "") + "},\n"
                        + "        connection_options={\"paths\": paths, \"recurse\": " + py(b.path("Recurse").asBoolean(true)) + "},\n        transformation_ctx=" + id + ",\n    )\n";
            }
            case "S3ParquetSource" -> {
                params.add("paths=" + py(b.path("Paths")));
                body = "    return glueContext.create_dynamic_frame.from_options(\n        connection_type=\"s3\",\n        format=\"parquet\",\n"
                        + "        connection_options={\"paths\": paths, \"recurse\": " + py(b.path("Recurse").asBoolean(true)) + "},\n        transformation_ctx=" + id + ",\n    )\n";
            }
            case "S3JsonSource" -> {
                params.add("paths=" + py(b.path("Paths")));
                body = "    return glueContext.create_dynamic_frame.from_options(\n        connection_type=\"s3\",\n        format=\"json\",\n"
                        + "        format_options={\"multiline\": " + py(b.path("Multiline").asBoolean(false))
                        + (b.hasNonNull("JsonPath") && !b.path("JsonPath").asText().isEmpty() ? ", \"jsonPath\": " + py(b.path("JsonPath").asText()) : "") + "},\n"
                        + "        connection_options={\"paths\": paths, \"recurse\": " + py(b.path("Recurse").asBoolean(true)) + "},\n        transformation_ctx=" + id + ",\n    )\n";
            }
            case "S3CatalogSource", "CatalogSource" -> {
                String pred = b.path("PartitionPredicate").asText("");
                body = "    return glueContext.create_dynamic_frame.from_catalog(\n        database=" + py(b.path("Database").asText()) + ",\n        table_name=" + py(b.path("Table").asText())
                        + ",\n" + (pred.isEmpty() ? "" : "        push_down_predicate=" + py(pred) + ",\n") + "        transformation_ctx=" + id + ",\n    )\n";
            }
            case "ApplyMapping" -> {
                StringBuilder m = new StringBuilder();
                for (JsonNode e : b.path("Mapping")) {
                    if (e.path("Dropped").asBoolean(false)) continue;
                    String from = join(e.path("FromPath"));
                    String to = e.path("ToKey").asText(from);
                    m.append("            (").append(py(from)).append(", ").append(py(e.path("FromType").asText("string"))).append(", ")
                     .append(py(to)).append(", ").append(py(e.path("ToType").asText("string"))).append("),\n");
                }
                body = "    return ApplyMapping.apply(\n        frame=" + params.get(1) + ",\n        mappings=[\n" + m + "        ],\n        transformation_ctx=" + id + ",\n    )\n";
            }
            case "SelectFields" -> body = "    return SelectFields.apply(frame=" + params.get(1) + ", paths=" + py(paths(b.path("Paths"))) + ", transformation_ctx=" + id + ")\n";
            case "DropFields" -> body = "    return DropFields.apply(frame=" + params.get(1) + ", paths=" + py(paths(b.path("Paths"))) + ", transformation_ctx=" + id + ")\n";
            case "RenameField" -> body = "    return RenameField.apply(frame=" + params.get(1) + ", old_name=" + py(join(b.path("SourcePath"))) + ", new_name=" + py(join(b.path("TargetPath"))) + ", transformation_ctx=" + id + ")\n";
            case "DropNullFields" -> body = "    return DropNullFields.apply(frame=" + params.get(1) + ", transformation_ctx=" + id + ")\n";
            case "Filter" -> {
                List<String> exprs = new ArrayList<>();
                for (JsonNode e : b.path("Filters")) exprs.add(filterExpr(n, e));
                String op = "OR".equalsIgnoreCase(b.path("LogicalOperator").asText("AND")) ? " or " : " and ";
                String expr = exprs.isEmpty() ? "True" : String.join(op, exprs);
                body = "    return Filter.apply(frame=" + params.get(1) + ", f=lambda row: " + expr + ", transformation_ctx=" + id + ")\n";
            }
            case "Join" -> {
                if (n.inputs().size() != 2) throw ApiError.badRequest("Join '" + n.name() + "' needs exactly 2 inputs");
                String a = params.get(1), c = params.get(2);
                List<String> ka = new ArrayList<>(), kb = new ArrayList<>();
                for (JsonNode col : b.path("Columns")) {
                    List<String> keys = new ArrayList<>();
                    for (JsonNode k : col.path("Keys")) keys.add(join(k));
                    if (col.path("From").asText().equals(n.inputs().get(0))) ka.addAll(keys); else kb.addAll(keys);
                }
                String type = b.path("JoinType").asText("equijoin");
                if (type.equals("equijoin") || type.equals("inner")) {
                    body = "    return Join.apply(frame1=" + a + ", frame2=" + c + ", keys1=" + py(ka) + ", keys2=" + py(kb) + ", transformation_ctx=" + id + ")\n";
                } else {
                    StringBuilder cond = new StringBuilder("[");
                    for (int i = 0; i < Math.min(ka.size(), kb.size()); i++) cond.append(i > 0 ? ", " : "").append("a[").append(py(ka.get(i))).append("] == b[").append(py(kb.get(i))).append("]");
                    cond.append("]");
                    body = "    a = " + a + ".toDF()\n    b = " + c + ".toDF()\n    return DynamicFrame.fromDF(a.join(b, " + cond + ", how=" + py(type) + "), glueContext, " + id + ")\n";
                }
            }
            case "DropDuplicates" -> {
                List<String> cols = paths(b.path("Columns"));
                body = "    return DynamicFrame.fromDF(" + params.get(1) + ".toDF().dropDuplicates(" + (cols.isEmpty() ? "" : py(cols)) + "), glueContext, " + id + ")\n";
            }
            case "Aggregate" -> {
                StringBuilder aggs = new StringBuilder();
                for (JsonNode a : b.path("Aggs")) {
                    String col = join(a.path("Column"));
                    String fn = a.path("AggFunc").asText("count");
                    aggs.append(aggs.length() > 0 ? ", " : "").append("F.").append(fn).append("(").append(py(col)).append(").alias(").append(py(col + "_" + fn)).append(")");
                }
                if (aggs.length() == 0) aggs.append("F.count(F.lit(1)).alias(\"count\")");
                body = "    return DynamicFrame.fromDF(" + params.get(1) + ".toDF().groupBy(*" + py(paths(b.path("Groups"))) + ").agg(" + aggs + "), glueContext, " + id + ")\n";
            }
            case "SparkSQL" -> {
                StringBuilder views = new StringBuilder();
                for (JsonNode al : b.path("SqlAliases")) {
                    String from = al.path("From").asText();
                    String var = names.get(from);
                    if (var == null || !n.inputs().contains(from)) throw ApiError.badRequest("SparkSQL '" + n.name() + "' aliases '" + from + "' which is not one of its inputs");
                    views.append("    ").append(var).append(".toDF().createOrReplaceTempView(").append(py(al.path("Alias").asText())).append(")\n");
                }
                body = views + "    return DynamicFrame.fromDF(glueContext.spark_session.sql(" + py(b.path("SqlQuery").asText()) + "), glueContext, " + id + ")\n";
            }
            case "CustomCode" -> {
                StringBuilder dfc = new StringBuilder("{");
                for (int i = 0; i < n.inputs().size(); i++) {
                    Dag.Node in = dag.nodes.get(n.inputs().get(i));
                    dfc.append(i > 0 ? ", " : "").append(py(in.name())).append(": ").append(names.get(in.id()));
                }
                dfc.append("}");
                body = "    out = " + b.path("ClassName").asText("MyTransform") + "(glueContext, DynamicFrameCollection(" + dfc + ", glueContext))\n    return out.select(list(out.keys())[0])\n";
            }
            case "Union" -> {
                StringBuilder u = new StringBuilder("    df = " + params.get(1) + ".toDF()\n");
                for (int i = 2; i < params.size(); i++) u.append("    df = df.union(").append(params.get(i)).append(".toDF())\n");
                if ("DISTINCT".equalsIgnoreCase(b.path("UnionType").asText("ALL"))) u.append("    df = df.distinct()\n");
                body = u + "    return DynamicFrame.fromDF(df, glueContext, " + id + ")\n";
            }
            case "S3DirectTarget", "S3GlueParquetTarget" -> {
                params.add("path=" + py(b.path("Path").asText()));
                boolean glueParquet = n.type().equals("S3GlueParquetTarget");
                String format = glueParquet ? "glueparquet" : b.path("Format").asText("parquet").toLowerCase();
                String comp = b.path("Compression").asText("");
                String fo = glueParquet ? "        format_options={\"compression\": " + py(comp.isEmpty() ? "snappy" : comp.toLowerCase()) + "},\n"
                        : comp.isEmpty() || comp.equalsIgnoreCase("none") || comp.equalsIgnoreCase("uncompressed") ? "" : "        format_options={\"compression\": " + py(comp.toLowerCase()) + "},\n";
                body = "    glueContext.write_dynamic_frame.from_options(\n        frame=" + params.get(1) + ",\n        connection_type=\"s3\",\n        format=" + py(format) + ",\n" + fo
                        + "        connection_options={\"path\": path, \"partitionKeys\": " + py(paths(b.path("PartitionKeys"))) + "},\n        transformation_ctx=" + id + ",\n    )\n    return " + params.get(1) + "\n";
            }
            case "S3CatalogTarget" -> body = "    glueContext.write_dynamic_frame.from_catalog(\n        frame=" + params.get(1) + ",\n        database=" + py(b.path("Database").asText()) + ",\n        table_name=" + py(b.path("Table").asText())
                    + ",\n        additional_options={\"partitionKeys\": " + py(paths(b.path("PartitionKeys"))) + "},\n        transformation_ctx=" + id + ",\n    )\n    return " + params.get(1) + "\n";
            default -> throw unsupported(n, n.type());
        }
        f.append("def ").append(names.get(n.id())).append("(").append(String.join(", ", params)).append("):\n")
         .append("    \"\"\"").append(n.type()).append(": ").append(n.name().replace("\"", "'")).append("\"\"\"\n").append(body);
        return f.toString();
    }

    static ApiError unsupported(Dag.Node n, String what) {
        return ApiError.badRequest("node '" + n.name() + "' (" + n.id() + ") is " + what + ", which Keel cannot generate yet; express it as SparkSQL or CustomCode");
    }

    /** One Filter row: `Values[0]` is the column, `Values[1..]` the operand(s). */
    static String filterExpr(Dag.Node n, JsonNode e) {
        List<String> vals = new ArrayList<>();
        for (JsonNode v : e.path("Values")) vals.add(value(v));
        if (vals.isEmpty()) throw ApiError.badRequest("Filter '" + n.name() + "' has a condition with no values");
        String x = vals.get(0);
        String y = vals.size() > 1 ? vals.get(1) : "None";
        String op = e.path("Operation").asText("EQ").toUpperCase();
        String expr = switch (op) {
            case "EQ" -> x + " == " + y;
            case "NE" -> x + " != " + y;
            case "LT" -> x + " < " + y;
            case "GT" -> x + " > " + y;
            case "LTE" -> x + " <= " + y;
            case "GTE" -> x + " >= " + y;
            case "IN" -> x + " in " + (vals.size() > 2 ? "[" + String.join(", ", vals.subList(1, vals.size())) + "]" : "[" + y + "]");
            case "BETWEEN" -> "(" + y + " <= " + x + " <= " + (vals.size() > 2 ? vals.get(2) : y) + ")";
            case "CONTAINS" -> "(" + y + " in str(" + x + "))";
            case "STARTS_WITH" -> "str(" + x + ").startswith(" + y + ")";
            case "ENDS_WITH" -> "str(" + x + ").endswith(" + y + ")";
            case "REGEX" -> "re.search(" + y + ", str(" + x + ")) is not None";
            case "LIKE", "ILIKE" -> "re.fullmatch(re.escape(" + y + ").replace(\"%\", \".*\").replace(\"_\", \".\"), str(" + x + ")" + (op.equals("ILIKE") ? ", re.IGNORECASE" : "") + ") is not None";
            case "NULL", "ISNULL" -> x + " is None";
            case "NOT_NULL" -> x + " is not None";
            case "ZERO_LENGTH" -> "len(str(" + x + ")) == 0";
            default -> throw ApiError.badRequest("Filter '" + n.name() + "' uses operation " + op + " which Keel does not know");
        };
        return e.path("Negated").asBoolean(false) ? "not (" + expr + ")" : "(" + expr + ")";
    }

    private static String value(JsonNode v) {
        JsonNode val = v.path("Value");
        String s = val.isArray() ? (val.size() > 0 ? val.get(0).asText() : "") : val.asText("");
        if ("COLUMNEXTRACTED".equalsIgnoreCase(v.path("Type").asText("CONSTANT"))) return "row[" + py(s) + "]";
        if (s.matches("-?\\d+")) return s;
        if (s.matches("-?\\d*\\.\\d+")) return s;
        if (s.equalsIgnoreCase("true") || s.equalsIgnoreCase("false")) return s.equalsIgnoreCase("true") ? "True" : "False";
        return py(s);
    }

    static String separator(String s) {
        return switch (s.toLowerCase()) {
            case "tab" -> "\t";
            case "pipe" -> "|";
            case "semicolon" -> ";";
            case "ctrla" -> String.valueOf((char) 1);
            default -> ",";
        };
    }

    static String quote(String q) {
        return switch (q.toLowerCase()) { case "single_quote" -> "'"; case "disabled" -> "-1"; case "quillemet" -> "«"; default -> "\""; };
    }

    /** Paths in the API are lists of path segments; joined with `.` they are Glue field paths. */
    public static String join(JsonNode path) {
        if (path.isTextual()) return path.asText();
        List<String> parts = new ArrayList<>();
        for (JsonNode p : path) parts.add(p.asText());
        return String.join(".", parts);
    }

    public static List<String> paths(JsonNode arr) {
        List<String> out = new ArrayList<>();
        for (JsonNode p : arr) out.add(join(p));
        return out;
    }

    // ---- Python literals -------------------------------------------------------------------------

    public static String py(Object o) {
        if (o == null) return "None";
        if (o instanceof JsonNode n) return pyNode(n);
        if (o instanceof Boolean b) return b ? "True" : "False";
        if (o instanceof Number num) return num.toString();
        if (o instanceof List<?> l) { StringBuilder b = new StringBuilder("["); for (int i = 0; i < l.size(); i++) b.append(i > 0 ? ", " : "").append(py(l.get(i))); return b.append("]").toString(); }
        return pyString(o.toString());
    }

    private static String pyNode(JsonNode n) {
        if (n.isNull() || n.isMissingNode()) return "None";
        if (n.isBoolean()) return n.asBoolean() ? "True" : "False";
        if (n.isNumber()) return n.numberValue().toString();
        if (n.isTextual()) return pyString(n.asText());
        if (n.isArray()) { StringBuilder b = new StringBuilder("["); for (int i = 0; i < n.size(); i++) b.append(i > 0 ? ", " : "").append(pyNode(n.get(i))); return b.append("]").toString(); }
        StringBuilder b = new StringBuilder("{");
        boolean first = true;
        for (Iterator<Map.Entry<String, JsonNode>> it = n.fields(); it.hasNext();) {
            Map.Entry<String, JsonNode> e = it.next();
            b.append(first ? "" : ", ").append(pyString(e.getKey())).append(": ").append(pyNode(e.getValue()));
            first = false;
        }
        return b.append("}").toString();
    }

    public static String pyString(String s) {
        StringBuilder b = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '\\' -> b.append("\\\\");
                case '"' -> b.append("\\\"");
                case '\n' -> b.append("\\n");
                case '\r' -> b.append("\\r");
                case '\t' -> b.append("\\t");
                default -> { if (c < 0x20) b.append(String.format("\\x%02x", (int) c)); else b.append(c); }
            }
        }
        return b.append('"').toString();
    }
}
