# Generated by Keel from dag.json. Do not edit by hand: custom logic belongs in a SparkSQL or CustomCode node.
import re
import sys

from awsglue.context import GlueContext
from awsglue.dynamicframe import DynamicFrame, DynamicFrameCollection
from awsglue.job import Job
from awsglue.transforms import ApplyMapping, DropFields, DropNullFields, Filter, Join, RenameField, SelectFields
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from pyspark.sql import functions as F


def customers_csv(glueContext, paths=["s3://example-bucket/customers/"]):
    """S3CsvSource: Customers CSV"""
    return glueContext.create_dynamic_frame.from_options(
        connection_type="s3",
        format="csv",
        format_options={"withHeader": True, "separator": ",", "quoteChar": "\""},
        connection_options={"paths": paths, "recurse": True},
        transformation_ctx="n-customers",
    )


def orders_csv(glueContext, paths=["s3://example-bucket/orders/"]):
    """S3CsvSource: Orders CSV"""
    return glueContext.create_dynamic_frame.from_options(
        connection_type="s3",
        format="csv",
        format_options={"withHeader": True, "separator": ",", "quoteChar": "\""},
        connection_options={"paths": paths, "recurse": True},
        transformation_ctx="n-orders",
    )


def map_orders(glueContext, orders_csv):
    """ApplyMapping: Map orders"""
    return ApplyMapping.apply(
        frame=orders_csv,
        mappings=[
            ("order_id", "string", "order_id", "int"),
            ("customer_id", "string", "customer_id", "int"),
            ("status", "string", "status", "string"),
            ("amount", "string", "amount", "double"),
        ],
        transformation_ctx="n-map",
    )


def only_paid(glueContext, map_orders):
    """Filter: Only paid"""
    return Filter.apply(frame=map_orders, f=lambda row: (row["status"] == "paid") and (row["amount"] > 0), transformation_ctx="n-paid")


def join_customers(glueContext, only_paid, customers_csv):
    """Join: Join customers"""
    return Join.apply(frame1=only_paid, frame2=customers_csv, keys1=["customer_id"], keys2=["customer_id"], transformation_ctx="n-join")


def revenue_by_country(glueContext, join_customers):
    """Aggregate: Revenue by country"""
    return DynamicFrame.fromDF(join_customers.toDF().groupBy(*["country"]).agg(F.sum("amount").alias("amount_sum"), F.count("order_id").alias("order_id_count")), glueContext, "n-agg")


def revenue_csv(glueContext, revenue_by_country, path="s3://example-bucket/out/revenue/"):
    """S3DirectTarget: Revenue CSV"""
    glueContext.write_dynamic_frame.from_options(
        frame=revenue_by_country,
        connection_type="s3",
        format="csv",
        connection_options={"path": path, "partitionKeys": []},
        transformation_ctx="n-out",
    )
    return revenue_by_country


def main():
    args = getResolvedOptions(sys.argv, ["JOB_NAME"])
    sc = SparkContext.getOrCreate()
    glueContext = GlueContext(sc)
    job = Job(glueContext)
    job.init(args["JOB_NAME"], args)
    f_customers_csv = customers_csv(glueContext)
    f_orders_csv = orders_csv(glueContext)
    f_map_orders = map_orders(glueContext, f_orders_csv)
    f_only_paid = only_paid(glueContext, f_map_orders)
    f_join_customers = join_customers(glueContext, f_only_paid, f_customers_csv)
    f_revenue_by_country = revenue_by_country(glueContext, f_join_customers)
    f_revenue_csv = revenue_csv(glueContext, f_revenue_by_country)
    job.commit()


if __name__ == "__main__":
    main()
