/** Every node type Glue Studio offers, by family, with its UI name. Codegen supports a subset (schema.ts); the rest edit as JSON and deploy as-is. */
export type Family = { title: string; category: 'source' | 'transform' | 'target'; types: [string, string][] }
export const CATALOG: Family[] = [
  { title: 'Sources · Amazon S3', category: 'source', types: [['S3CsvSource', 'S3 · CSV'], ['S3JsonSource', 'S3 · JSON'], ['S3ParquetSource', 'S3 · Parquet'], ['S3ExcelSource', 'S3 · Excel'], ['S3CatalogSource', 'S3 · Data Catalog table'], ['S3DeltaSource', 'S3 · Delta Lake'], ['S3CatalogDeltaSource', 'Catalog · Delta Lake'], ['S3HudiSource', 'S3 · Hudi'], ['S3CatalogHudiSource', 'Catalog · Hudi'], ['S3CatalogIcebergSource', 'Catalog · Iceberg']] },
  { title: 'Sources · Catalog & databases', category: 'source', types: [['CatalogSource', 'Data Catalog'], ['CatalogDeltaSource', 'Data Catalog · Delta'], ['CatalogHudiSource', 'Data Catalog · Hudi'], ['CatalogIcebergSource', 'Data Catalog · Iceberg'], ['RelationalCatalogSource', 'Relational DB (Catalog)'], ['MySQLCatalogSource', 'MySQL'], ['PostgreSQLCatalogSource', 'PostgreSQL'], ['OracleSQLCatalogSource', 'Oracle'], ['MicrosoftSQLServerCatalogSource', 'SQL Server'], ['DynamoDBCatalogSource', 'DynamoDB'], ['DynamoDBELTConnectorSource', 'DynamoDB (ELT)'], ['RedshiftSource', 'Redshift (legacy)'], ['AmazonRedshiftSource', 'Amazon Redshift'], ['SnowflakeSource', 'Snowflake'], ['DirectJDBCSource', 'JDBC']] },
  { title: 'Sources · Streaming & connectors', category: 'source', types: [['DirectKinesisSource', 'Kinesis'], ['CatalogKinesisSource', 'Kinesis (Catalog)'], ['DirectKafkaSource', 'Kafka'], ['CatalogKafkaSource', 'Kafka (Catalog)'], ['AthenaConnectorSource', 'Athena connector'], ['JDBCConnectorSource', 'JDBC connector'], ['SparkConnectorSource', 'Spark connector'], ['ConnectorDataSource', 'Connector data source']] },
  { title: 'Transforms', category: 'transform', types: [['ApplyMapping', 'Change Schema'], ['SelectFields', 'Select Fields'], ['DropFields', 'Drop Fields'], ['RenameField', 'Rename Field'], ['Filter', 'Filter'], ['Join', 'Join'], ['Union', 'Union'], ['Aggregate', 'Aggregate'], ['DropDuplicates', 'Drop Duplicates'], ['DropNullFields', 'Drop Null Fields'], ['FillMissingValues', 'Fill Missing Values'], ['SplitFields', 'Split Fields'], ['SelectFromCollection', 'Select From Collection'], ['Merge', 'Merge'], ['Spigot', 'Spigot'], ['SparkSQL', 'SQL Query'], ['CustomCode', 'Custom Transform'], ['DynamicTransform', 'Dynamic Transform'], ['Recipe', 'Data Preparation Recipe'], ['PIIDetection', 'Detect Sensitive Data'], ['EvaluateDataQuality', 'Evaluate Data Quality'], ['EvaluateDataQualityMultiFrame', 'Evaluate Data Quality (multi)'], ['Route', 'Conditional Router']] },
  { title: 'Targets · Amazon S3', category: 'target', types: [['S3DirectTarget', 'S3 (CSV/JSON/Parquet/…)'], ['S3GlueParquetTarget', 'S3 · Glue Parquet'], ['S3CatalogTarget', 'S3 · Data Catalog table'], ['S3DeltaDirectTarget', 'S3 · Delta Lake'], ['S3DeltaCatalogTarget', 'Catalog · Delta Lake'], ['S3HudiDirectTarget', 'S3 · Hudi'], ['S3HudiCatalogTarget', 'Catalog · Hudi'], ['S3IcebergDirectTarget', 'S3 · Iceberg'], ['S3IcebergCatalogTarget', 'Catalog · Iceberg'], ['S3HyperDirectTarget', 'S3 · Tableau Hyper'], ['GovernedCatalogTarget', 'Governed table']] },
  { title: 'Targets · Databases & connectors', category: 'target', types: [['CatalogTarget', 'Data Catalog'], ['MySQLCatalogTarget', 'MySQL'], ['PostgreSQLCatalogTarget', 'PostgreSQL'], ['OracleSQLCatalogTarget', 'Oracle'], ['MicrosoftSQLServerCatalogTarget', 'SQL Server'], ['RedshiftTarget', 'Redshift (legacy)'], ['AmazonRedshiftTarget', 'Amazon Redshift'], ['SnowflakeTarget', 'Snowflake'], ['JDBCConnectorTarget', 'JDBC connector'], ['SparkConnectorTarget', 'Spark connector'], ['ConnectorDataTarget', 'Connector data target']] },
]
export const UI_NAME: Record<string, string> = Object.fromEntries(CATALOG.flatMap((f) => f.types))
export function uiName(type: string): string { return UI_NAME[type] ?? type.replace(/([a-z])([A-Z])/g, '$1 $2') }
